# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\publish_mapping.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCasePublishMapping(HttpRunner):

    config = (
        Config("testcase description")
        .base_url("http://121.14.41.140:5683")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("get ProductNo")
            .get("/api/bamboo/PdPublish/generateProductNo")
            .with_headers(
                **{
                    "Host": "121.14.41.140:5683",
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "Authorization": "${get_authorization()}",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
                    "Access-Control-Max-Age": "86000",
                    "Referer": "http://121.14.41.140:5683/bamboo/develop/release",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_cookies(
                **{"Authorization": "${get_authorization()}", "appId": "${get_appId()}"}
            )
            .extract()
            .with_jmespath("body.data", "ProductNo")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 200)
            .assert_equal("body.msg", "操作成功")
        ),
        Step(
            RunRequest("PdPublish/addOrUpdateSpu")
            .post("/api/bamboo/PdPublish/addOrUpdateSpu")
            .with_headers(
                **{
                    "Host": "121.14.41.140:5683",
                    "Connection": "keep-alive",
                    "Content-Length": "7890",
                    "Accept": "application/json, text/plain, */*",
                    "Origin": "http://121.14.41.140:5683",
                    "Authorization": "${get_authorization()}",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
                    "Access-Control-Max-Age": "86000",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Referer": "http://121.14.41.140:5683/bamboo/develop/release",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_cookies(
                **{"Authorization": "${get_authorization()}", "appId": "${get_appId()}"}
            )
            .with_json(
                {
                    "attrList": [
                        {
                            "attributeCategoryId": "1350019738823368706",
                            "attributeCategoryName": "裙子风格",
                            "attributeId": "1350019291349852162",
                            "attributeName": "裙子风格",
                            "attributeValueList": [
                                {"id": "1350019291400183809", "value": "轻熟"},
                                {"id": "1350019291416961026", "value": "性感"},
                                {"id": "1350019291425349633", "value": "青春"},
                            ],
                            "id": "1350019973452734465",
                            "isMulti": 1,
                            "isMust": 0,
                            "productCategoryId": "1108",
                            "sort": 1,
                            "value": ["1350019291416961026"],
                        },
                        {
                            "attributeCategoryId": "1350019786537771010",
                            "attributeCategoryName": "连衣裙裙长",
                            "attributeId": "1350019563686010881",
                            "attributeName": "裙长",
                            "attributeValueList": [
                                {"id": "1350019564189327361", "value": "长"},
                                {"id": "1350019564176744449", "value": "中"},
                                {"id": "1350019564201910274", "value": "短"},
                            ],
                            "id": "1350019973419180033",
                            "isMulti": 0,
                            "isMust": 1,
                            "productCategoryId": "1108",
                            "sort": 2,
                            "value": "1350019564176744449",
                        },
                    ],
                    "id": "",
                    "aliProductId": "",
                    "allowIncrease": "100",
                    "attributeValueList": [
                        {
                            "attributeId": "1350019973452734465",
                            "attributeValueIds": ["1350019291416961026"],
                        },
                        {
                            "attributeId": "1350019973419180033",
                            "attributeValueIds": ["1350019564176744449"],
                        },
                    ],
                    "belongDepartmentId": "ea8c89892df24b59b20618077e9f922c",
                    "belongDepartmentName": "创新孵化中心",
                    "bodyImageList": [
                        {
                            "sort": 0,
                            "image": "9de3c087b37e422e8921fbed6ec205a5.jpg",
                            "imageMd5": "D3F8FFABE8CC39CBE601810BAF2E01A9",
                            "imageType": "1",
                        },
                        {
                            "sort": 1,
                            "image": "5c48fdad07394c3bbd11cd943e4d2c38.jpg",
                            "imageMd5": "BCD4CDD8C7DF6830ADB83451440DB411",
                            "imageType": "1",
                        },
                    ],
                    "categoryId": "1108",
                    "chooseDepartmentId": "637cbcb5553d43e99731f0a5cf644f52",
                    "chooseDepartmentName": "系统运营部",
                    "chooseUserId": "1334512653855080450",
                    "chooseUserName": "李国龙",
                    "coverImage": "b43e2e647c0943a2870ae5c33b98b538.jpg",
                    "developRequire": "",
                    "imageList": [
                        {
                            "image": "b43e2e647c0943a2870ae5c33b98b538.jpg",
                            "url": "http://orderplus-cloud-test.oss-cn-hongkong.aliyuncs.com/orderPlus/b43e2e647c0943a2870ae5c33b98b538.jpg",
                            "imageMd5": "2DE8EA91E183CD9098BCA1BD8FD15022",
                            "sort": 0,
                            "imageType": "1",
                        },
                        {
                            "image": "6f54ce4efea34887b30c0dfac5bb4727.jpg",
                            "url": "http://orderplus-cloud-test.oss-cn-hongkong.aliyuncs.com/orderPlus/6f54ce4efea34887b30c0dfac5bb4727.jpg",
                            "imageMd5": "C4C2C8E4880B6B41053BAED530E9D3AB",
                            "sort": 1,
                            "imageType": "1",
                        },
                    ],
                    "operateType": 3,
                    "playBoardNo": "",
                    "productDesc": '<table id="table"><tbody><tr class="firstRow"><td>裙子风格</td><td>性感</td></tr><tr><td>裙长</td><td>中</td></tr></tbody></table><table id="table"><tbody><tr class="firstRow"><td>尺码</td><td>衣长</td><td>胸围</td><td>腰围</td><td>臀围</td></tr><tr><td>S</td><td>102</td><td>82</td><td>66</td><td>86</td></tr><tr><td>m</td><td>103</td><td>86</td><td>70</td><td>90</td></tr><tr><td>l</td><td>104</td><td>90</td><td>74</td><td>94</td></tr></tbody></table><p><img src="http://orderplus-cloud-test.oss-cn-hongkong.aliyuncs.com/orderPlus/9de3c087b37e422e8921fbed6ec205a5.jpg?x-oss-process=image/resize,m_lfit,h_600,w_600" style="margin-right: 32px;"/><br/><img src="http://orderplus-cloud-test.oss-cn-hongkong.aliyuncs.com/orderPlus/5c48fdad07394c3bbd11cd943e4d2c38.jpg?x-oss-process=image/resize,m_lfit,h_600,w_600" style="margin-right: 32px;"/><br/>\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>',
                    "productNo": "$ProductNo",
                    "productSupplyType": "2",
                    "productTestType": "",
                    "productType": "2",
                    "brandId": "",
                    "purchaseGuideMaxPrice": "",
                    "purchaseGuideMinPrice": "",
                    "referenceProductNo": "",
                    "referenceType": "",
                    "sizeTableContent": '[{"size":"S","add1":"82","n397":"102","n499":"66","n820":"86"},{"size":"m","add1":"86","n397":"103","n499":"70","n820":"90"},{"size":"l","add1":"90","n397":"104","n499":"74","n820":"94"}]',
                    "sizeTableHeader": '[{"prop":"size","label":"尺码"},{"prop":"n397","label":"衣长"},{"prop":"add1","label":"胸围"},{"prop":"n499","label":"腰围"},{"prop":"n820","label":"臀围"}]',
                    "skuList": [
                        {
                            "连衣裙尺码连衣裙颜色": "s，白，",
                            "skuDesc": "s,白",
                            "skuSaleDesc": "s,白",
                            "skuSaleRelate": "s,白",
                            "length": "",
                            "width": "",
                            "height": "",
                            "id": "",
                            "isGroup": False,
                            "isSplit": False,
                            "salePrice": "",
                            "skuSuppose": [
                                {"count": "", "id": "", "skuId": "", "spuId": ""}
                            ],
                            "skuGroupInfoList": [],
                            "spuId": "",
                            "sort": "",
                            "supplyPrice": "233",
                            "weight": "222",
                            "image": "05512a2a69bd434fb1b2a5c4ff18c124.jpg",
                            "stock": "3",
                            "aliSpecId": "",
                            "imageMd5": "C19BB63F3AB97D5F68AA6A4A158F6B8E",
                            "sku": "",
                            "eightImage": "",
                            "eightGuige": "",
                        },
                        {
                            "连衣裙尺码连衣裙颜色": "s，黑，",
                            "skuDesc": "s,黑",
                            "skuSaleDesc": "s,黑",
                            "skuSaleRelate": "s,黑",
                            "length": "",
                            "width": "",
                            "height": "",
                            "id": "",
                            "isGroup": False,
                            "isSplit": False,
                            "salePrice": "",
                            "skuSuppose": [
                                {"count": "", "id": "", "skuId": "", "spuId": ""}
                            ],
                            "skuGroupInfoList": [],
                            "spuId": "",
                            "sort": "",
                            "supplyPrice": "233",
                            "weight": "222",
                            "image": "71e6a73924464f5cb758cd6ce061f968.jpg",
                            "stock": "3",
                            "aliSpecId": "",
                            "imageMd5": "2DE8EA91E183CD9098BCA1BD8FD15022",
                            "sku": "",
                            "eightImage": "",
                            "eightGuige": "",
                        },
                        {
                            "连衣裙尺码连衣裙颜色": "M，白，",
                            "skuDesc": "M,白",
                            "skuSaleDesc": "M,白",
                            "skuSaleRelate": "M,白",
                            "length": "",
                            "width": "",
                            "height": "",
                            "id": "",
                            "isGroup": False,
                            "isSplit": False,
                            "salePrice": "",
                            "skuSuppose": [
                                {"count": "", "id": "", "skuId": "", "spuId": ""}
                            ],
                            "skuGroupInfoList": [],
                            "spuId": "",
                            "sort": "",
                            "supplyPrice": "233",
                            "weight": "222",
                            "image": "05512a2a69bd434fb1b2a5c4ff18c124.jpg",
                            "stock": "3",
                            "aliSpecId": "",
                            "imageMd5": "C19BB63F3AB97D5F68AA6A4A158F6B8E",
                            "sku": "",
                            "eightImage": "",
                            "eightGuige": "",
                        },
                        {
                            "连衣裙尺码连衣裙颜色": "M，黑，",
                            "skuDesc": "M,黑",
                            "skuSaleDesc": "M,黑",
                            "skuSaleRelate": "M,黑",
                            "length": "",
                            "width": "",
                            "height": "",
                            "id": "",
                            "isGroup": False,
                            "isSplit": False,
                            "salePrice": "",
                            "skuSuppose": [
                                {"count": "", "id": "", "skuId": "", "spuId": ""}
                            ],
                            "skuGroupInfoList": [],
                            "spuId": "",
                            "sort": "",
                            "supplyPrice": "233",
                            "weight": "222",
                            "image": "71e6a73924464f5cb758cd6ce061f968.jpg",
                            "stock": "3",
                            "aliSpecId": "",
                            "imageMd5": "2DE8EA91E183CD9098BCA1BD8FD15022",
                            "sku": "",
                            "eightImage": "",
                            "eightGuige": "",
                        },
                        {
                            "连衣裙尺码连衣裙颜色": "L，白，",
                            "skuDesc": "L,白",
                            "skuSaleDesc": "L,白",
                            "skuSaleRelate": "L,白",
                            "length": "",
                            "width": "",
                            "height": "",
                            "id": "",
                            "isGroup": False,
                            "isSplit": False,
                            "salePrice": "",
                            "skuSuppose": [
                                {"count": "", "id": "", "skuId": "", "spuId": ""}
                            ],
                            "skuGroupInfoList": [],
                            "spuId": "",
                            "sort": "",
                            "supplyPrice": "233",
                            "weight": "222",
                            "image": "05512a2a69bd434fb1b2a5c4ff18c124.jpg",
                            "stock": "3",
                            "aliSpecId": "",
                            "imageMd5": "C19BB63F3AB97D5F68AA6A4A158F6B8E",
                            "sku": "",
                            "eightImage": "",
                            "eightGuige": "",
                        },
                        {
                            "连衣裙尺码连衣裙颜色": "L，黑，",
                            "skuDesc": "L,黑",
                            "skuSaleDesc": "L,黑",
                            "skuSaleRelate": "L,黑",
                            "length": "",
                            "width": "",
                            "height": "",
                            "id": "",
                            "isGroup": False,
                            "isSplit": False,
                            "salePrice": "",
                            "skuSuppose": [
                                {"count": "", "id": "", "skuId": "", "spuId": ""}
                            ],
                            "skuGroupInfoList": [],
                            "spuId": "",
                            "sort": "",
                            "supplyPrice": "233",
                            "weight": "222",
                            "image": "71e6a73924464f5cb758cd6ce061f968.jpg",
                            "stock": "3",
                            "aliSpecId": "",
                            "imageMd5": "2DE8EA91E183CD9098BCA1BD8FD15022",
                            "sku": "",
                            "eightImage": "",
                            "eightGuige": "",
                        },
                    ],
                    "sourceUrl": "",
                    "specAttributeInfoList": [
                        {
                            "specAttributeCategoryId": "1351071518323712001",
                            "specAttributeCategoryName": "连衣裙全尺寸",
                            "specAttributeId": "1351070924305408001",
                            "specAttributeName": "连衣裙尺码",
                            "specAttributeValueList": [
                                {
                                    "convertSourceName": "s",
                                    "name": "",
                                    "specAttributeValueId": "",
                                },
                                {
                                    "convertSourceName": "M",
                                    "name": "",
                                    "specAttributeValueId": "",
                                },
                                {
                                    "convertSourceName": "L",
                                    "name": "",
                                    "specAttributeValueId": "",
                                },
                            ],
                        },
                        {
                            "specAttributeCategoryId": "1351071391655731201",
                            "specAttributeCategoryName": "黑白连衣裙",
                            "specAttributeId": "1351071100571033602",
                            "specAttributeName": "连衣裙颜色",
                            "specAttributeValueList": [
                                {
                                    "convertSourceName": "白",
                                    "name": "",
                                    "specAttributeValueId": "",
                                },
                                {
                                    "convertSourceName": "黑",
                                    "name": "",
                                    "specAttributeValueId": "",
                                },
                            ],
                        },
                    ],
                    "specAttributeList": [
                        {"cnName": "连衣裙尺码", "valueList": ["s", "M", "L"]},
                        {"cnName": "连衣裙颜色", "valueList": ["白", "黑"]},
                    ],
                    "stockLogisticsAttribute": "1",
                    "stockLogisticsDesc": "测试备注_${get_nowtime()}",
                    "supplierName": "",
                    "supplierType": "",
                    "supplyPrice": "233",
                    "tag": "",
                    "title": "${get_product_name()}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCasePublishMapping().test_start()
