# NOTE: Generated By HttpRunner v3.1.4
# FROM: testapi\sysApproveProcess.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseSysapproveprocess(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("$sysApproveProcessType")
            .get(
                "http://121.14.41.140:8020/bamboo/sysApproveProcess/getDataBySpuId/$spuid/$type"
            )
            .with_headers(
                **{
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "Authorization": "${get_authorization()}",
                    "Connection": "keep-alive",
                    "accept": "*/*",
                }
            )
            .with_cookies(
                **{"Authorization": "${get_authorization()}", "appId": "${get_appId()}"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 200)
            .assert_equal("body.msg", "操作成功")
            .assert_equal("body.data.needPresale", "$needPresale")
            .assert_equal("body.data.needInfringement", "$needInfringement")
        ),
    ]


if __name__ == "__main__":
    TestCaseSysapproveprocess().test_start()
